name: g-gold

services:
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:7.0
    volumes:
      - "./.mongodb/data:/data/db"
      - "./.mongodb/config:/data/configdb"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=bn_parse
      - MONGODB_DATABASE=bitnami_parse
      - MONGODB_PASSWORD=bitnami123

  parse:
    container_name: parse
    image: bitnami/parse:7
    ports:
      - "1337:1337"
    volumes:
      - "./.parse/data:/bitnami/parse"
    depends_on:
      - mongodb
    environment:
      - PARSE_DATABASE_HOST=127.0.0.1
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=bn_parse
      - PARSE_DATABASE_NAME=bitnami_parse
      - PARSE_DATABASE_PASSWORD=bitnami123
      - PARSE_SERVER_MASTER_KEY_IPS=0.0.0.0/0

  parse-dashboard:
    container_name: parse-dashboard
    image: "bitnami/parse-dashboard:latest"
    ports:
      - "8070:4040"
    volumes:
      - "parse_dashboard_data:/bitnami"
    depends_on:
      - parse
    environment:
      - PARSE_DASHBOARD_PARSE_HOST=127.0.0.1
      - PARSE_DASHBOARD_APP_NAME=TestApp

  website:
    container_name: website
    build:
      context: packages/web
      target: development
    volumes:
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./packages:/app/packages
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

  proxy:
    container_name: nginx2
    build:
      context: "nginx"
      target: development
    ports:
      - 8888:80
      - 3032:3032
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on:
      - website
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/default.conf
          target: /etc/nginx/conf.d/default.conf

volumes:
  parse_dashboard_data:
    driver: local
