name: g-gold
services:
  mongo1:
    image: mongo:7.0
    container_name: gold.mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      # disable: true
      test: echo "try { rs.status().ok } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 1m
      timeout: 30s
      start_period: 0s
      start_interval: 10s
      retries: 3
    volumes:
      - "./.mongodb/data:/data/db"
      - "./.mongodb/config:/data/configdb"

  # redis:
  #   image: redis:7.4-alpine
  #   container_name: gold.redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./.redis:/bitnami/redis/data

  api:
    container_name: gold.api
    build:
      context: packages/api
      target: development
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    depends_on:
      # - redis
      - mongo1
    volumes:
      - ./package.json:/wdir/package.json
      - ./node_modules:/wdir/node_modules
      - ./packages/api:/wdir/packages/api
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./packages/api/src
    #       target: /app/packages/api/src

    #     - action: sync+restart
    #       path: ./packages/api/package.json
    #       target: /app/packages/api/package.json

    #     - action: rebuild
    #       path: ./packages/api/Dockerfile

    #     - action: rebuild
    #       path: package.json

  panel:
    container_name: gold.panel
    build:
      context: packages/panel
      target: development
    volumes:
      - ./package.json:/wdir/package.json
      - ./node_modules:/wdir/node_modules
      - ./packages:/wdir/packages
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    develop:
      watch:
        - action: sync+restart
          path: ./packages/panel/src
          target: /wdir/packages/panel/src

        - action: sync+restart
          path: ./packages/panel/package.json
          target: /wdir/packages/panel/package.json

        - action: sync+restart
          path: ./packages/api/src
          target: /wdir/packages/api/src

        - action: sync+restart
          path: ./packages/api/package.json
          target: /wdir/packages/api/package.json

        - action: rebuild
          path: ./packages/panel/Dockerfile

        - action: rebuild
          path: package.json

  proxy:
    container_name: gold.nginx
    build:
      context: "nginx"
      target: development
    ports:
      - 8888:80
      - 3032:3032
    volumes:
      - ./public:/usr/share/nginx/html
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/default.conf
          target: /etc/nginx/conf.d/default.conf
